# Generated by Django 5.1.4 on 2025-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0012_adminlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
