# Generated by Django 5.1.4 on 2025-04-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0018_login_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Confirmpassword',
            new_name='confirmpassword',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Username',
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
